package com.espherika.healthbot.kie

import ar.com.espherika.healthbot.model.*;

declare MenorEdad
   edad : int
   nombre : String
end

declare Persona
	edad : int
	nombre : String
end


rule "Persona Menor de edad"
when
    $p: Persona( edad < 18 )
then	
	MenorEdad menor=new MenorEdad();
	menor.setEdad($p.getEdad());
	menor.setNombre($p.getNombre());
	insert(menor);
	System.out.println($p.getNombre());
end

rule "Ciudadano Menor de edad"
when
    $p: Ciudadano( edad < 18 )
then	
	MenorEdad menor=new MenorEdad();
	menor.setEdad($p.getEdad());
	menor.setNombre($p.getNombre());
	insert(menor);
	System.out.println($p.getNombre());
end

rule "Insert mayor Edad"
when
then
	Persona p=new Persona();
	p.setEdad(17);
	p.setNombre("carlos");
	insert(p);
	System.out.println("Regla Insertar persona");
end


